# Generated by Django 5.2.6 on 2025-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('other', 'Other')], max_length=20)),
                ('ministry_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('event_name', models.CharField(max_length=150)),
                ('event_state', models.CharField(max_length=100)),
                ('event_district', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=300)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('no_of_participants', models.PositiveIntegerField()),
                ('event_description', models.TextField(max_length=1000)),
                ('event_pictures', models.FileField(blank=True, null=True, upload_to='event_images/')),
                ('event_videos', models.FileField(blank=True, null=True, upload_to='event_videos/')),
                ('youtube_links', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
