# Generated by Django 5.2.6 on 2025-11-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_remove_eventapplication_event_pictures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapplication',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='ministry_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='user_type',
            field=models.CharField(choices=[('Ministry', 'Ministry'), ('State', 'State'), ('College', 'College'), ('Institute', 'Institute'), ('School', 'School'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='video',
            field=models.FileField(default='NULL', upload_to='event_videos/'),
            preserve_default=False,
        ),
    ]
