# Generated by Django 5.2.6 on 2025-11-13 06:21

import Registration.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_eventapplication_district_eventapplication_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventapplication',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces allowed')]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='event_description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='event_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='ministry_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces allowed')]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='no_of_participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='youtube_links',
            field=models.TextField(blank=True, null=True, validators=[Registration.models.validate_youtube_links]),
        ),
    ]
